FROM python:3.5
COPY requirements.txt /tmp
RUN ["pip", "install", "-r", "/tmp/requirements.txt"]
RUN ["pip", "install", "pylint"]
RUN ["pip", "install", "coverage"]
# Our setup.py requires pbr. Think of a better way to use it
# without polluting this image.
RUN ["pip", "install", "pbr>=1.8.0"]
RUN ["rm", "/tmp/requirements.txt"]
